import word_counter

counter = word_counter.NumCounter()
urls = counter.create_gutenberg_urls(num_books=800, start_index=2101)
# to 2100
counter.iterate_through_urls(urls=urls, filename="word_frequency.txt")
# counter.remove_one_counts("word_frequency.txt")
# df = counter.normalize_counts(filename="word_frequency.txt")
# print(df)
counter.remove_symbols_from_df("word_frequency.txt", "word_frequency.txt", "é")
counter.remove_symbols_from_df("word_frequency.txt", "word_frequency.txt", "1")
counter.remove_symbols_from_df("word_frequency.txt", "word_frequency.txt", "2")
counter.remove_symbols_from_df("word_frequency.txt", "word_frequency.txt", "3")
counter.remove_symbols_from_df("word_frequency.txt", "word_frequency.txt", "4")
counter.remove_symbols_from_df("word_frequency.txt", "word_frequency.txt", "5")
counter.remove_symbols_from_df("word_frequency.txt", "word_frequency.txt", "“")
counter.remove_symbols_from_df("word_frequency.txt", "word_frequency.txt", "—")
counter.remove_symbols_from_df("word_frequency.txt", "word_frequency.txt", "")
counter.remove_symbols_from_df("word_frequency.txt", "word_frequency.txt", "")
counter.remove_symbols_from_df("word_frequency.txt", "word_frequency.txt", '’', "'")
